### PR TITLE
Feature/update to latest server

### PR DESCRIPTION
**Pull request by przerwap**

### CODE REVIEW

**Comment by calda** [comment]
I thought Bukkit died a few years ago -- what's this about? @przerwap

**Comment by przerwap** [comment]
@calda ¯\\\_(ツ)\_/¯
These guys seem to still be using it.
It does appear that the jar used to launch the server is now named "Spigot", but the dependency they both use is `craftbukkit-1.12.2.jar` ? I've no idea, I haven't touched any of this stuff in like 5 years.

**Comment by calda** [comment]
Unrelated, but do you know what happened to voxelwiki.com? Does that old content still exist anywhere, even in like an offline backup? I’d really like to get ahold of an archive of that.

**Comment by przerwap** [comment]
There is always the wayback machine 
https://web.archive.org/web/20140318143202/http://voxelwiki.com:80/minecraft/Main_Page

**Comment by Rezel** [comment]
As far as I know everything was taken down when TVB died, though you can also access it through the waybackmachine.com

**Comment by calda** [comment]
I chatted with deamon5550 (nick) on twitter. He has a .zip of VoxelWiki backed up, and he may be bringing back online (I hope!).

**Pull request merged**
